const getData = new Promise((resolve, reject) => {
//     reject('55560');
// });

// getData
//     .then(data => console.log(data + 10))
//     .catch(err => console.log("Err:", err));